FROM php:7.0-fpm

RUN docker-php-ext-install mysqli pdo_mysql

#RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
 #   && docker-php-ext-install -j$(nproc) gd
